### ISSUE TITLE
Can't get AllPixel working on a Pi Zero

### ISSUE THREAD

**Issue by xtalker** [ManiacalLabs/AllPixel#10]
Tried too many times, install goes ok but just can't get pixels working.  These are WS2811's LED Pixel Digital Diffused 12mm RGB Light P68 Waterproof.

Here are the steps I used to setup the Pi Zero (several times) from scratch:
`Download: 2018-11-13-raspbian-stretch-lite.zip
Use etcher to create SD card with above for a Pi Zero

sudo apt-get update
sudo apt-get dist-upgrade
sudo apt-get install python3-pip
pip3 install pyserial --upgrade --ignore-installed
sudo pip3 install bibliopixel
sudo apt-get install libatlas-base-dev  (fixes "libf77blas.so.3: cannot open shared object file: 
   No such  file or directory" error)

strip.py:
	import bibliopixel
	# causes frame timing information to be output
	bibliopixel.log.setLogLevel(bibliopixel.log.DEBUG)

	# Load driver for the AllPixel
	from bibliopixel.drivers.serial import *
	# set number of pixels & LED type here
	driver = Serial(num = 3, ledtype = LEDTYPE.WS2811)

	# load the LEDStrip class
	from bibliopixel.layout import *
	led = Strip(driver)

	# load channel test animation
	from bibliopixel.animation import StripChannelTest
	anim = StripChannelTest(led)

	try:
	    # run the animation
	    anim.run()
	except KeyboardInterrupt:
	    # Ctrl+C will exit the animation and turn the LEDs offs
	    led.all_off()
	    led.update()

pi@raspberrypi:~/allpixel $ python3 strip.py
WARNING - deprecated - util.setLogLevel
INFO - devices - Using COM Port: /dev/ttyACM0, Device ID: 0, Device Ver: 0
WARNING - deprecated - BaseAnimation.run
DEBUG - animation_threading - Animation starts on main thread

(leds do nothing here)`

These leds and Allpixel board work fine on my Mac (running python 2.7) so I've eliminated a hardware issue.

Please help, Xmas is coming!

**Comment by adammhaile** [comment]
How are you powering the LEDs?

**Comment by xtalker** [comment]
At the moment there are only 9 leds so power is from the Allpixel's USB.  As I mentioned these leds with the same Allpixel work fine on my Mac using Python 2.7

**Comment by adammhaile** [comment]
The USB ports on the Raspberry Pi, especially the Zero, are not suitable
for powering LEDs from. They cannot provide enough power. You'll need to
use the barrel jack input on the AllPixel to power the LEDs.

**Comment by xtalker** [comment]
Hey Adam,  I just tried this with a 5v, 3a external power supply on the Allpixel barrel jack but still no luck.

**Comment by adammhaile** [comment]
Just in case, can you set your log level line to this?
`bibliopixel.log.setLogLevel(bibliopixel.log.FRAME)`

I want to make sure that you are actually getting frames written out.
I'm honestly stumped otherwise... a picture of how it's all connected would help. I've never used an AllPixel on a Pi Zero, just a full size Pi. 
what's weird is that I would expect if it didn't work that it would show a failure in the script output. But it seems to still be sending data to the AllPixel just fine. That's why I thought it was power.
If you by chance have a regular Pi I recommend trying it with that.... just swap the SD card into the other Pi, it should work. 
I'm very suspect of the Pi Zero's weird USB port. Even with external LED power the AllPixel still powers it's microcontroller from the USB connection and I wonder if it's not being powered like it needs to be.

**Comment by xtalker** [comment]
Put the same sd card into an rPi2 and made the setLogLevel change you mentioned, still nothing.

`pi@raspberrypi:~/allpixel $ python3 strip.py
WARNING - deprecated - util.setLogLevel
INFO - devices - Using COM Port: /dev/ttyACM0, Device ID: 0, Device Ver: 0
WARNING - deprecated - BaseAnimation.run
DEBUG - animation_threading - Animation starts on main thread`

Does that  device/version ID make sense?  I used this setup  a few years ago (the python 2.7 version) and had no issues at all!

Thanks for your help!
Bob

**Comment by adammhaile** [comment]
With that log change it should output a new debug line every ~1 second with
frame timings. If that's not happening then I'd say that it's not actually
sending updates.
Wait.... you said it worked on Mac and I remember you said it was python
2.7 which I dismissed as incorrect because the latest bibliopixel is Python
3 only. Are you using the older BiblioPixel 2 on the Mac?

**Comment by adammhaile** [comment]
@xtalker - Ah... there's a bit of a regression in the latest couple releases.
Please install v3.4.30
`pip uninstall -y bibliopixel; pip install bibliopixel==3.4.30`

**Comment by adammhaile** [comment]
For my own reference, this is related to this: https://github.com/ManiacalLabs/BiblioPixel/issues/1084

**Comment by xtalker** [comment]
That fixed it! Works on both the rpi2 & rpi0!
Thanks again!
Bob
