### ISSUE TITLE
Can't get AllPixel working with > 500 pixels.

### ISSUE THREAD

**Issue by menthon** [ManiacalLabs/AllPixel#12]
Hi!

Really enjoying AllPixel Mini and the Accompanying BiblioPixel library. But still can't get the library working with the 700 pixels promised. When initialising driver with more than 500 leds, got the following:

>>> driver = Serial(num = 750, ledtype = LEDTYPE.APA102, c_order = ChannelOrder.BGR)
INFO - devices - Using COM Port: /dev/ttyACM2, Device ID: 0, Device Ver: 0
INFO - driver - Reconfigure and reboot needed!
Waiting for controller to restart...
ERROR - return_codes - 3: Wrong number of pixels for device.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.6/site-packages/bibliopixel/drivers/serial/driver.py", line 69, in __init__
    raise_error(resp)
  File "/home/user/.local/lib/python3.6/site-packages/bibliopixel/drivers/return_codes.py", line 36, in raise_error
    raise BiblioSerialError(print_error(error))
bibliopixel.drivers.return_codes.BiblioSerialError: None

Anyone got past this?

**Comment by adammhaile** [comment]
First glance... you are trying 750 which is definitely not supported.
Second: Please post this over on our support forum: https://groups.google.com/forum/#!forum/maniacal-labs-users
We don't do issue or support tracking here.
Also I expect this to be a BiblioPixel issue.... over on the good group page please post your *complete* code for this so that I can try it out and attempt to debug.
